### ISSUE TITLE
Titlepage.x

### ISSUE THREAD

**Issue by acabal** [alemacgo/charles-darwin_the-origin-of-species#1]
- Should simply be "The Origin of Species", make sure to leave padding on the side of the svg per our specs
- viewbox should be sized to fit the contents plus the padding, you can copy the viewport from https://github.com/standardebooks/apsley-cherry-garrard_the-worst-journey-in-the-world/blob/master/images/titlepage.svg

**Comment by alescode** [comment]
thanks! done
