### ISSUE TITLE
General chapter issues

### ISSUE THREAD

**Issue by acabal** [alemacgo/charles-darwin_the-origin-of-species#12]
- `<title>` tags must be titlecased, you can use the `titlecase` tool to do this
- No roman numerals in `<title>` tags; use 1, 2, 3, 4 instead of I, II, III, IV, etc.
- Individual titles/sentences in the bridghead should be regular-cased--in other words, capitalize first word, not others.
- `<h3>` tags should be titlecased
- Wrap sections headed with `<h3>` in `<section id="url-friendly-id" epub:type="subchapter">`
- Anything with an `<h3>` tag should go in `toc.xhtml`.  So, please add links to the specific ids for those elements into the ToC.  You can do that by adding a sub-`<ol>` element to contain the children for each chapter.

**Comment by alescode** [comment]
@acabal These subchapters aren't numbered in the original text. Should I still add them as an `<ol>` element, or would `<ul>` be more appropriate?

**Comment by acabal** [comment]
They should be `<ol>` because they are **o**rdered in the text.
