### ISSUE TITLE
endnotes.xhtml

### ISSUE THREAD

**Issue by acabal** [alemacgo/charles-darwin_the-origin-of-species#13]
Many works in here need italics instead of quotes, if they meet our italics rules in the typography manual: https://standardebooks.org/contribute/typography#names-and-titles

**Comment by acabal** [comment]
Also, add a space between the last word in the endnote, and the backlink

**Comment by acabal** [comment]
W.S. Dallas needs a space between the initials, `<abbr class="name">`, and the corresponding CSS rules for abbr.name in `local.css`

Make sure to search for other names that meet this rule in the text.  See step 8 in the step by step guide for a regex that will help you find these: https://standardebooks.org/contribute/producing-an-ebook-step-by-step

**Comment by alescode** [comment]
@acabal where do I find the catalog that contains the different types of italics? e.g.  
```<i epub:type="se:name.vessel.ship">Bounty</i>```

**Comment by acabal** [comment]
See http://standardebooks.org/vocab/1.0

The formatting is rough, but you can see how your example is represented in the vocab with a hierarchy.  Each level becomes a `.` in `epub:type`

**Comment by alescode** [comment]
@acabal I just stumbled upon
```
In June, 1859, Professor Huxley gave a lecture before the Royal Institution on the “Persistent Types of Animal Life”. Referring to such cases, he remarks...
```
Can we add `se.name.event.lecture` to the vocab?

**Comment by acabal** [comment]
No, things that were spoken/performed once and not printed are generally left without semantics.  Especially since this one says "the topic was "such and such"", not "the lecture entitled "such and such"".

This would be comparable to how we don't italicize the titles of short songs, short stories, etc.  See the typography manual: https://standardebooks.org/contribute/typography#names-and-titles
